/**
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * @param {string} s
 * @param {string} t
 * @return {string}
 */
function findTheDifference(s: string, t: string): string {
  const table: Record<string, number> = {};
  let output;

  for (let i = 0; i < t.length; i++) {
    const tChar = t.charAt(i);

    if (table[tChar] > 0) {
      table[tChar]++;
    } else {
      table[tChar] = 1;
    }
  }

  for (let i = 0; i < s.length; i++) {
    const sChar = s.charAt(i);

    table[sChar]--;
  }

  for (const item in table) {
    if (table[item] === 1) {
      output = item;
      break;
    }
  }

  return output;
}

export default findTheDifference;
